version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Date-Converter__java_app
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://db:3306/dateconverterDB",        
            "spring.datasource.username" : "root",
            "spring.datasource.password" : "123", 
            "spring.jpa.hibernate.ddl-auto" : "update"      
            }'
    depends_on:
      - db

  db:
    image: 'mysql:5.6'
    container_name: MySQL__database
    environment:
      - MYSQL_DATABASE=dateconverterDB
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_ROOT_USER=admin
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123
    volumes:
      - dbvolum:/var/lib/mySQL
    ports:
      - "3306:3306"
volumes:
  dbvolum:
